[tool.poetry]
name = "repl_python3_beta_DataCrawling"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.3.4"
pyproj = "^3.2.1"
ogr = "^0.30.0"
Shapely = "^1.7.1"
plotly = "^5.3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
